spring:
  application:
    name: poc-spring-session-jdbc
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost/postgres}
    username: ${DATABASE_USERNAME:default}
    password: ${DATABASE_PASSWORD:}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  session:
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      initialize-schema: always
      table-name: SPRING_SESSION
server:
  port: {SERVER_PORT:8080}