spring:
  application:
    name: poc-spring-session-jdbc
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost/postgres}
    username: ${DATABASE_USERNAME:default}
    password: ${DATABASE_PASSWORD:}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  session:
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      initialize-schema: always
      table-name: SPRING_SESSION

server:
  port: {SERVER_PORT:8080}

oauth:
  google:
    client-id: {OAUTH_GOOGLE_CLIENT_ID}
    client-secret: {OAUTH_GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:${server.port}/auth/sign-in/oauth/google/callback
    scopes: https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile, openid