spring:
  application:
    name: poc-spring-session-jdbc
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  session:
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-h2.sql
      initialize-schema: embedded
      table-name: SPRING_SESSION